
development:
  adapter: mysql
  database: lovdbyless_development
  username: root
  password: akkuakku
  encoding: utf8

test:
  adapter: mysql
  database: lovdbyless_test
  username: root
  password: akkuakku
  encoding: utf8
